### ISSUE TITLE
Pérdida de barra de buscador.

### ISSUE THREAD

**Issue by ForeroAnonimo** [ehtiotumolas/forocoches-premium#2]
Al activar el bloqueo de publicidad, se elimina tambien la barra de buscador de hilos :(
Version foro antigua. Extension 1.6.0

Dejo imagen. https://i.imgur.com/Gam9MmY.png

![Captura](https://user-images.githubusercontent.com/132367826/235684826-35b8f3bc-41f9-4d0f-b3c1-4b0e8f1c00e0.PNG)

**Comment by ehtiotumolas** [comment]
Muchas gracias por reportar el bug.

He subido una nueva versión arreglando esto (1.6.1).
Tardará unos minutos en ser aceptada por Google.

Dejaré otro mensaje cuando esté lista.

![image](https://user-images.githubusercontent.com/131691063/235692509-08e0a519-2213-4200-bdea-107acc2dd5bc.png)

**Comment by ForeroAnonimo** [comment]
Solucionado muy rapido. Gracias.
PD: 3 cuentas me tumbó ilitri este fin de semana por promocionar la extension en el foro. Realmente me banearon 1 y otras 2 por compartir IP. Que curioso que al banearmela tambien me borro los hilos que hice donde se mencionaba la extension y el resto no.

Ahora ya solo me queda mi cuenta principal y no puedo promocionar mas.

**Comment by ehtiotumolas** [comment]
Muchas gracias. Me alegro mucho de que te guste tanto la extensión que la promocionarte! Una pena lo del foro... A mi me pasó lo mismo con dos cuentas: una baneada y la otra por ip. Pero bueno, ahora la extensión sale la segunda en Google al poner Forocoches Premium así que espero que la gente la encuentre más fácil.
